# github markdown rendering engine
author: i05nagai
title: memo
baseurl: /memorandum
theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: article
    values:
      categories: [article]
  -
    scope:
      path: book
    values:
      categories: [book]
  -
    scope:
      path: machine_learning
    values:
      categories: [machine_learning]
  -
    scope:
      path: math
    values:
      categories: [math]
  -
    scope:
      path: thesis
    values:
      categories: [thesis]
  -
    scope:
      path: vim
    values:
      categories: [vim]
  -
    scope:
      path: ""
    values:
      layout: slate_page

exclude: [vendor]
plugin:
# Github default plugins
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
# user defined plugins
- jekyll-seo-tag

# following items are set by Gihutb io. We cannot override.
lsi: false
safe: true
incremental: false
# GFM style code highlight syntax
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
markdown: kramdown
